# Generated by Django 4.1.3 on 2023-03-15 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'solution',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Sol',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user',
        ),
    ]
